# 1. Use Node.js official image
FROM node:20

# 2. Set working directory
WORKDIR /app

# 3. Copy package files
COPY package*.json ./

# 4. Install dependencies
RUN npm install

# 5. Copy the rest of the code
COPY . .

# 6. Build TypeScript
RUN npm run build

# 7. Expose port 
EXPOSE 8000

# 8. Start app 
CMD ["npm", "start"]
